### ISSUE TITLE
パッケージ管理

### ISSUE THREAD

**Issue by Ryusei-0407** [GEN222/WebAI#1]
READMEに書いてある、パッケージごとのライブラリを手動でやるのは好ましくないから、実際に開発してるPCで

```sh
pip freeze > requirements.txt
```

って実行すると、`pip freeze` コマンドでパッケージとそのバージョンを出力してくれるから、それをrequirements.txtで出力して、手元で動かしたいときは、

```sh
pip install -r requirements.txt
```

で済ませて上げた方が良いと思う

**Comment by GEN222** [comment]
ありがとう！！めっちゃ参考になる！！
